### ISSUE TITLE
conv_fail and result

### ISSUE THREAD

**Issue by rgrinberg** [Drup/tyre#10]
I'm wondering why conv_fail doesn't have the following signature instead:

```
val conv_fail : ('a -> ('b, string) Result.result) -> ('b -> 'a) -> 'a t -> 'b t
```

Seems like this gives extra flexibility with respect to error handling.

**Comment by Drup** [comment]
I had to look up the signature to realize that it wasn't like that. Very good idea. Can you PR it ? :)

**Comment by rgrinberg** [comment]
So that would mean changing `('a, 'b) conv` to allow for `Result.result`, right?

**Comment by Drup** [comment]
Yes, and `Tyre.error` too.

**Comment by rgrinberg** [comment]
Ok. And what to do about `~name`? We could still keep it around for things like
pp'ing. I'd say getting rid of it or making it optional is best.

**Comment by rgrinberg** [comment]
ping?

**Comment by Drup** [comment]
huum, I'm not sure. I would tend to say that we should keep it.

I wonder if we shouldn't use `('b, exn) Result.result` instead. That would provide good handling of exceptions thrown by converters.

**Comment by rgrinberg** [comment]
You mean should right? Yeah, I think there's a lot of sense to just use exceptions here.

**Comment by Drup** [comment]
Yes.

**Comment by Drup** [comment]
Done!
