### ISSUE TITLE
Dubious choice of operators

### ISSUE THREAD

**Issue by rgrinberg** [Drup/tyre#3]
* The applicative family of operators is being overloaded here `<*>`, `*>`, `<*`. I think a better option here would be something that hints at concatenation

* `<?>` should be `<|>`. `<?>` is usually reserved for adding error handling.

**Comment by Drup** [comment]
I agree on `<|>`. error handling is done quite differently in `tyre`, so the parallel with angstorm doesn't really make sense. 

According to [this](http://caml.inria.fr/pub/docs/manual-ocaml/expr.html), `<&>` would work ok (`<&>`, `&>` and `<&` have the same priority and associatitivy). The downside is that it's a bit ugly and annoying to type.

**Comment by rgrinberg** [comment]
I'm with the `&`. On a qwerty keyword without a numpad, there's not even a difference between typing the 2 anyway.

**Comment by rgrinberg** [comment]
@Drup so is `<|>` settled?

**Comment by Drup** [comment]
Yes.

**Comment by Drup** [comment]
Everything is renamed!
