### ISSUE TITLE
Tyre advice needed

### ISSUE THREAD

**Issue by rgrinberg** [Drup/tyre#4]
Messing around with tyre and getting code that isn't totally satisfactory. For example:

``` ocaml
type ip = char * char * char * char

let try_ f x = try Some (f x) with _ -> None

let ip : ip Tyre.re =
  let byte =
    let re = Tyre.regex (Re.repn Re.digit 1 (Some 3)) in
    Tyre.conv ~name:"byte"
      (try_ (fun s -> Char.chr (int_of_string s)))
      (fun c -> string_of_int (Char.code c)) re in
  let open Tyre in
  let (<.>) a b = (a <* ".") <*> b in
  Tyre.conv ~name:"ip"
    (fun (((a, b), c), d) -> Some (a, b, c, d))
    (fun (a, b, c, d) -> (((a, b), c),d))
    (byte <.> byte <.> byte <.> byte)
  |> compile
```

Any tips on how to improve this code? Perhaps some new combinators are needed?

**Comment by Drup** [comment]
Which part would you like to simplify exactly ? We could probably remove the need for the `try_` helper.

Do you think the `byte` combinator is standard enough to be included ? I don't exactly object, but I'm not sure I ever saw it outside of an IP address.

**Comment by Drup** [comment]
We could also expose a `tuple` combinator (or several `tupleN` combinators ...).

**Comment by rgrinberg** [comment]
`try_` is mentioned in your ocamldoc so it's another argument to add it. I don't feel too strongly about it.

I don't think byte is particularly useful, but it definitely seems like its more hassle than you'd expect to read a length bounded integer. That's a fairly common use.

The ugliest bit to me is how a fixed element, string separated record is handled. It's quite a common use case.

**Comment by rgrinberg** [comment]
I would be even happy with a combinator that puts the elements into a list but lets me apply the length assertions somehow.

**Comment by Drup** [comment]
We could change the type of `rep` from `'a t -> 'a gen t` to `?min:int -> ?max:int -> 'a t -> 'a gen t` and do the same for `list`, `terminated_list` and `separated_list`.

**Comment by Drup** [comment]
```ocaml
  let (<.>) a b = (a <* ".") <*> b in
  Tyre.conv ~name:"ip"
    (fun (((a, b), c), d) -> Some (a, b, c, d))
    (fun (a, b, c, d) -> (((a, b), c),d))
    (byte <.> byte <.> byte <.> byte)
```

would be replaced by 

```
Tyre.conv ~name:"ip"
  (function [ a ; b ; c ; d ] -> Some (a, b, c, d) | _ -> None)
  (fun (a, b, c, d) -> [a;b;c;d])
  (separated_list ~min:4 ~max:4 ~sep:"." byte)
```

I'm not convinced that's much better than a tuple4 combinator, tbh. It also mean that this pattern need to be optimized (it would be very inefficient right now).

**Comment by rgrinberg** [comment]
If tuple4 lets me insert separators then that would be fine as well.

Also, how would you handle parsing something like a 3D point: `(float, float, float)`. The key here is that you can expect any number of spaces around the separators. I guess in my solution, you can update the `<.>` to handle the spaces. But it would be nice if the list parsers allowed for re's as separators.

**Comment by Drup** [comment]
In my head, `tuple4` would only be the `conv` part. In your case, it would be: 

```ocaml
let (<.>) a b = (a <* ".") <*> b in
Tyre.tuple4 (byte <.> byte <.> byte <.> byte)
```

Which looks quite good to me. If I understand correctly, you would like:

```ocaml
Tyre.tuple4 ~sep:(regex @@ Re.char '.') byte
```

I'm a bit worried about adding many combinators with various baroque conventions, that's the reason I sticked to something not too complicated (the API is already a bit too complicated/inconsistent for my taste). If we can come up with a rather clean design/convention for the set of extra combinators, then we can include them. 

My proposition for now would be to keep working on your current parser, then let's examine the current result and see what pattern emerges and see if we can come up with a nice general API for them.

**Comment by Drup** [comment]
[prototype crappy API](https://github.com/Drup/tyre/blob/54fb84b56585889dd12728f0c3b96bf8526666d1/src/tyre.mli#L150-L160).

**Comment by rgrinberg** [comment]
Ok here's another use case where parsing with tyre is unreasonably crappy
compared to normal regex. Suppose we'd like to parse a simple kv pair on 1 line:

```
key = value
```

In regex form this would be something like:

```
([^=]+)+[ \t]*=[ \t]*([^\n]*)\n
```

(the translation to re's combinators should be mechanical)

Where you can just post process the 2nd group with a strip.

Doing something like this in tyre however seems to be unreasonably verbose.
Perhaps I'm doing something wrong? Seems like a lot of my difficulty is stemming
from not figuring out a way handling optional whitespace in a way that doesn't
suck.

Can I see how you'd implement `(string * string) Tyre.t` in this case?

**Comment by rgrinberg** [comment]
Ok here's my attempt to do something a little more complex:

```ocaml
type section = string * (string * string) list

type ini =
  { named: section list
  ; anon: (string * string) list }

let take_till re = Re.(rep (compl [re])) |> Tyre.regex
let strip =
  Tyre.conv ~name:"strip" (fun a -> Some (String.trim a)) (fun x -> x)

let section_title =
  let open Tyre in
  let sec_name = ']' |> Re.char |> take_till |> strip in
  "[" *> sec_name <* "]"

let spaces = Tyre.regex (Re.rep Re.blank)

let entry : (string * string) Tyre.t =
  let open Tyre in
  let equal = Re.(seq [rep blank; char '='; rep blank]) |> regex in
  let until c = c |> Re.char |> take_till |> strip in
  let key =
    let open Re in
    [set "[]="]
    |> compl
    |> rep
    |> Tyre.regex
    |> strip in
  seq key ((equal, " = ") **> until '\n')
    
let empty_line =
  Re.(
    [rep (set " \t") ; char '\n']
    |> seq
    |> rep
  )
  |> Tyre.regex

let line t =
  let open Tyre in
  let nl_re = Re.(seq [rep blank ; char '\n']) in
  t <** (Tyre.regex nl_re, "\n")

let entry =
  let open Tyre in
  (empty_line, "") **> entry <** (empty_line, "")

let named_section =
  Tyre.seq (line section_title) (Tyre.terminated_list ~sep:"\n" entry)

let ini =
  Tyre.seq
    (Tyre.terminated_list ~sep:"\n" entry)
    (Tyre.list named_section)
  |> Tyre.conv ~name:"ini"
    (fun (anon, named) -> Some { anon ; named })
    (fun { anon ; named } -> (anon, named))

let sample_ini =
  { anon=[ "lang", "OCaml"
         ; "lib", "foo bar" ]
  ; named =
      [ "lib",
        [ "re", "1.5.0"
        ; "tyre", "> 1.5.0" ]
      ; "src",
        [ "one", "two"
        ; "xxx", "foo bar baz" ]
      ; "lib_test",
        [ "alcotest", "*" ]
      ]
  }

let sample_ini_str = Tyre.eval ini sample_ini

let sample_ini' = Tyre.exec (Tyre.compile ini) sample_ini_str
```

It's able to output a proper ini but unable to read it back. The error is a bit opaque so perhaps you could take a look.

**Comment by Drup** [comment]
You are hitting a bug that I fixed in the dev version. With the dev version, it seems to work perfectly. :)

**Comment by rgrinberg** [comment]
Ah thanks Drup. Would it be possible to make a release?

I'd like to show this stuff to someone and asking to pin would get in the way.

**Comment by Drup** [comment]
Yes, I'm making one right now.

**Comment by rgrinberg** [comment]
Some more points that came into my consideration after writing some more Tyre
parsers:

* The various `~sep` operations do need to be generalized. It's just too common
for such separators to have arbitrary space around them.

* There should be an easier way to deal with `compl`. For example, try parsing
something like `Firstname Lastname` with Tyre. Perhaps some sort of `take_while`
or `take_until` that only accepts a charset? I know this isn't the greatest idea
but this is definitely a pain point.

* More possibly useful space oriented combinators: `word` and `line` which will
read a string until a word or line boundary respectively.

**Comment by Drup** [comment]
Agreed. I will take a bit of time to think some more about the issues with `*>` and co.

**Comment by Drup** [comment]
The API was quite improved. Could you make separated bug report/PR for the remaining thing you want ?
